// <auto-generated />
namespace FFYP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jobsapprovedandbidslist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobsapprovedandbidslist));
        
        string IMigrationMetadata.Id
        {
            get { return "201610041620579_jobsapproved and bids list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
